### ISSUE TITLE
Upload failed (400): Binary wheel for an unsupported platform

### ISSUE THREAD

**Issue by np1** [meshy/pythonwheels#46]
Hi, I followed the instructions on the website (pip install wheel, universal=1 in setup.cfg) but when I tried uploading to pypi with: `python setup.py sdist bdist_wheel upload` I got the following output:

```
[...]
installing to build/bdist.linux-i686/wheel
running install
running install_egg_info
Copying mps.egg-info to build/bdist.linux-i686/wheel/mps-0.20.10.data/purelib/mps-0.20.10.egg-info
running install_scripts
creating build/bdist.linux-i686/wheel/mps-0.20.10.data/scripts
copying build/scripts-2.7/mps -> build/bdist.linux-i686/wheel/mps-0.20.10.data/scripts
changing mode of build/bdist.linux-i686/wheel/mps-0.20.10.data/scripts/mps to 775
creating build/bdist.linux-i686/wheel/mps-0.20.10.dist-info/WHEEL
running upload
Submitting dist/mps-0.20.10.tar.gz to https://pypi.python.org/pypi
Server response (200): OK
Submitting /f/h/projects/github/mps/dist/mps-0.20.10-cp27-none-linux_i686.whl to https://pypi.python.org/pypi
Upload failed (400): Binary wheel for an unsupported platform
```

This is the first time I have tried using wheel, does anyone know what the issue is?  This is the setup.py I was using: https://raw.githubusercontent.com/np1/mps/master/setup.py

**Comment by hickford** [comment]
> Upload failed (400): Binary wheel for an unsupported platform

The error message from PyPI would be more helpful if it explained which platform it thinks the wheel is.

**Comment by hickford** [comment]
I'm still struggling to upload my wheel. Can anyone help? 

1. Which platforms does PyPI support?
2. How does PyPI determine the platform of my wheel?

**Comment by meshy** [comment]
@hickford I think you should read @ghickman's [first comment](https://github.com/meshy/pythonwheels/issues/46#issuecomment-42521790) on this thread.

**Comment by hickford** [comment]
Pardon me. Copied question to https://bitbucket.org/pypa/wheel/issues/156/show-more-detail-in-binary-wheel-for-an

**Comment by meshy** [comment]
@hickford :+1: thanks `:)`

**Comment by todofixthis** [comment]
I tried a few strategies to work around this issue, but I'm not able to squash that generic `linux` platform tag.

In my case, it may be an issue with Travis CI; I've reached out to their support team for assistance.

In the meantime, here are some of the ways that I tried to work around this issue:

- Created two separate deployment tasks.  The first one only does an sdist, to ensure that a source distribution is always published, even if the wheel distros fail (https://github.com/todofixthis/pyota-ccurl/blob/1.0.8/.travis.yml#L19-L27).
- Tried adding a package to the project and declaring `packages` in `setup.py` (https://github.com/todofixthis/pyota-ccurl/blob/1.0.6/setup.py#L24).  Unfortunately, I got the same error (https://travis-ci.org/todofixthis/pyota-ccurl/jobs/287781659#L651).
- Tried `py_modules` instead of `packages` (https://github.com/todofixthis/pyota-ccurl/blob/1.0.8/setup.py#L24).  Same error (https://travis-ci.org/todofixthis/pyota-ccurl/jobs/287820028#L732).

If you were able to successfully work around this issue, please post what you tried; I could use some inspiration (:

**Comment by meshy** [comment]
@todofixthis I'm sorry, this isn't the right place to search for assistance on this issue. As [@ghickman explained](https://github.com/meshy/pythonwheels/issues/46#issuecomment-42521790) in the first comment here, this site is informational. Specifically, it's a graphic that visualises wheel support in the 360 most downloaded packages on PyPI.

I'm sure the folks at TravisCI will be able to help you better understand the issue, but if not, as @ghickman said, you should be able to also get assistance at the official wheel repo: https://bitbucket.org/pypa/wheel or the `#pypa` channel on freenode (IRC) where the developers of the spec and tools are around to lend a hand.
