### ISSUE TITLE
Site is 'unsafe' due to incorrect SSL cert

### ISSUE THREAD

**Issue by jaddison** [meshy/pythonwheels#84]
pythonwheels.com

Looks like it's using the default *.cloudfront.com cert, which (obviously) doesn't have pythonwheels.com as a common name on the cert.

**Comment by meshy** [comment]
Oh, thanks for pointing this out!

I'm not sure if we've ever deliberately supported https -- it's been so long since I set it up that I can't remember!

It would be nice if we did support https... it would require a little messing around with hosting. I'll pop it on my TODO list, but I'm afraid it's not high up at the moment, sorry.

**Comment by jaddison** [comment]
No worries - I noticed it and thought I'd pass it along. No rush for my sake. Cheers!

**Comment by jayvdb** [comment]
Google Search only lists the https site.

**Comment by ghickman** [comment]
@jayvdb – that's google promoting the HTTPS version of all sites, since you _can_ get to an HTTPS version they list it in search results.

**Comment by hugovk** [comment]
I think this can be closed, Google now only shows http://pythonwheels.com/ when searching for `python wheels`.

**Comment by meshy** [comment]
We're now serving the website through HTTPS \o/
