### ISSUE TITLE
This site is useless

### ISSUE THREAD

**Issue by ololoe** [meshy/pythonwheels#91]
Ipython is displayed as green, but installing on windows fails because there is no wheel for some binary dependency. So you have to check all dependencies or the site is just useless.

**Comment by hugovk** [comment]
Thank you for your feedback.  

IPython does have a wheel:
https://pypi.python.org/pypi/ipython/6.2.1

The primary purpose of this site is to drive adoption of the new wheel format amongst package maintainers. 

Please report installation problems directly with IPython:
https://github.com/ipython/ipython

**Comment by ololoe** [comment]
> IPython does have a wheel:

So? It has a wheel but I can't use it.

> Please report installation problems directly with IPython:

No, I want to report it here because it's your site providing useless information at this point.

**Comment by meshy** [comment]
Hello again @ololoe.

Thank you for your continued feedback.

I understand that you have found yourself frustrated because you are unable to install a package, despite expecting to be able to because a package is listed on pythonwheels.com as having a wheel.

Using pythonwheels.com to determine if you are able to install particular packages on Windows is a novel idea, but unfortunately is not the intent of the website.

As [I have previously explained](https://github.com/meshy/pythonwheels/issues/68):

> The pythonwheels.com website updates automatically once an hour, collecting and displaying information about the top 360 most downloaded packages from PyPI. In that update it will check to see if each package has any wheel packages, and make them green if appropriate.

@hugovk kindly summarised it better than I could: the "primary purpose of this site is to drive adoption of the new wheel format amongst package maintainers".

That said, I think you've struck upon a good idea! I do quite like the idea of a project that would be able to recurse through a library's dependencies and inform you of particular formats and platforms that it supports. I think I could use that website!

I encourage you to fork this repo and build it. You will find the business logic for communicating with PyPI's APIs in `utils.py`. When you're done, I would be interested to hear about it. Please return, and post a link.

In the meantime to avoid further unproductive discussion, I am going to lock this issue.

@hugovk, thank you for your support, and for remaining civil.
